site_name: "Microbiopy"
repo_url: "https://github.com/karmadolkar/microbiopy"

nav:
    - 'About': index.md
    - 'Filter Features' : ff.md
    - 'Principal Component Analysis' : pca.md      
    - 'Dependencies': dependencies.md
